apiVersion: v1
kind: Service
metadata:
  name: lb-a
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: app-a
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
