apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-b
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
      - name: wb
        image: gcr.io/whiteboard-479910/wb-app:latest
        env:
        - name: COUCHDB_LOCAL
          value: "http://admin:password@couchdb-0.couchdb.default.svc.cluster.local:5984"  # app-b pods target couchdb-1
        - name: DB_PREFIX
          value: "wb_"
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m          
            memory: 512Mi      
          limits:
            cpu: 1000m         
            memory: 1Gi 
